#!/bin/bash

#EMCC_DEBUG=1 /Users/shaafiee/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -o player.js 
#/Users/shaafiee/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=512MB -s ASSERTIONS=1 -s SAFE_HEAP=1 -o player.js 

if [ "$(uname)" == "Linux" ]; then
    emcc main.cpp -std=c++17 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s EXPORTED_FUNCTIONS="['_simpleFunction', '_doMain','_main']" -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=1024MB -o player.js 
    #emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -o player.js 
    #emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ALLOW_MEMORY_GROWTH=1 -o player.js 
    #emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -I -o player.js 
    #emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -o player.js 
else
    emcc main.cpp -std=c++17 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s EXPORTED_FUNCTIONS="['_simpleFunction', '_doMain', '_main']" -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_STACK=2000000 -s GLOBAL_BASE=2000000 -o player.js 
    #emcc main.cpp -std=c++17 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s EXPORTED_FUNCTIONS="['_simpleFunction', '_doMain', '_main']" -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=1024MB -o player.js 
    #~/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s EXPORTED_FUNCTIONS="['_simpleFunction', '_doMain', '_main']" -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -o player.js 
    #~/emsdk/clang/e1.38.31_64bit/llc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -o player.js 
    #~/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=1024MB -o player.js 
    #~/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=768MB -o player.js 
    #~/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -fsanitize=undefined -s TOTAL_MEMORY=750MB -s ALLOW_MEMORY_GROWTH=1 -o player.js 
    #~/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -s TOTAL_MEMORY=750MB -o player.js 
    #~/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -s SAFE_HEAP=1 -o player.js 
    #~/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -s ASSERTIONS=1 -o player.js 
fi

