#!/bin/sh

clang++ main.cpp -std=c++17 -w -g -o lottieplayer -lglfw -lGLEW -lGL -I/usr/include/SDL2 -D_REENTRANT -lSDL2

#g++ main.cpp -std=c++11 -w -g -o lottieplayer -framework SDL2  -framework OpenGL
