#!/bin/bash

#EMCC_DEBUG=1 /Users/shaafiee/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -o player.js 
#/Users/shaafiee/emsdk/fastcomp/emscripten/emcc main.cpp -std=c++17 -s WASM=1 -s USE_SDL=2 -O3 -o player.js 
llvm-g++ -std=c++17 -lSDL2 -O3 

